//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scissors.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiKey
    {
        public ApiKey()
        {
            this.ShortUrls = new HashSet<ShortUrl>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string AccessKey { get; set; }
        public bool isAdmin { get; set; }
        public bool isActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<ShortUrl> ShortUrls { get; set; }
    }
}
